packages:
  - apps/*
  - packages/*
catalog:
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.1
  eslint-config-next: ^15.5.3
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.34.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.2.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  jest: ^30.0.0
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/config": ^4.0.2
  "@nestjs/core": ^11.0.1
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/testing": ^11.0.1
  next: ^15.5.3
  "@next/eslint-plugin-next": ^15.5.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  tsconfig-paths: ^4.2.0
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  turbo: ^2.5.6
  typescript: 5.9.2
  typescript-eslint: ^8.40.0
  "@types/express": ^5.0.0
  "@types/jest": ^30.0.0
  "@types/node": ^22.15.3
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.1
  "@types/supertest": ^6.0.2
  "@mantine/core": ^8.3.1
  "@mantine/hooks": ^8.3.1
  "@mantine/carousel": ^8.3.1
  "@tabler/icons-react": ^3.0.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  clsx: ^2.1.1
  next-intl: ^4.3.9
  embla-carousel-autoplay: ^8.5.2
  prisma: 6.16.2
  "@prisma/client": 6.16.2
  "@nestjs/mapped-types": "*"
  "@nestjs/jwt": "^11.0.0"
  "@nestjs/passport": "^11.0.5"
  "passport-jwt": "^4.0.1"
  "@types/passport-jwt": "^4.0.1"
  "passport-local": "^1.0.0"
  "@types/passport-local": "^1.0.38"
  "cookie-parser": "^1.4.7"
  "@types/cookie-parser": "^1.4.9"
  "zod": "^4.1.9"
  "mantine-form-zod-resolver": "^1.3.0"
  "@mantine/form": "^8.3.1"
