packages:
  - apps/*
  - packages/*
catalog:
  axios: ^1.12.2
  bcrypt: ^6.0.0
  clsx: ^2.1.1
  cookie-parser: ^1.4.7
  dayjs: ^1.11.18
  dotenv: ^17.2.3
  embla-carousel-autoplay: ^8.5.2
  eslint: ^9.34.0
  eslint-config-next: 16.0.5
  eslint-config-prettier: ^10.1.1
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.34.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.2.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  express-session: ^1.18.2
  globals: ^16.3.0
  "@hello-pangea/dnd": ^18.0.1
  jest: ^30.0.0
  "@mantine/carousel": ^8.3.9
  "@mantine/core": ^8.3.9
  mantine-datatable: ^8.3.8
  "@mantine/dates": ^8.3.9
  "@mantine/dropzone": ^8.3.9
  "@mantine/form": ^8.3.9
  mantine-form-zod-resolver: ^1.3.0
  "@mantine/hooks": ^8.3.9
  "@mantine/notifications": ^8.3.9
  multer: ^2.0.2
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/config": ^4.0.2
  "@nestjs/core": ^11.0.1
  "@nestjs/jwt": ^11.0.0
  "@nestjs/mapped-types": "*"
  "@nestjs/passport": ^11.0.5
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/platform-socket.io": ^11.0.1
  "@nestjs/schedule": ^6.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/swagger": ^11.2.3
  "@nestjs/testing": ^11.0.1
  "@nestjs/websockets": ^11.0.1
  next: 16.0.5
  "@next/eslint-plugin-next": ^15.5.0
  next-intl: ^4.5.6
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prettier: ^3.6.2
  prisma: ^7.1.0
  "@prisma/adapter-pg": ^7.1.0
  "@prisma/client": ^7.1.0
  promptpay-qr: ^0.5.0
  qrcode.react: ^4.2.0
  "@quixo3/prisma-session-store": ^3.1.13
  react: 19.2.0
  react-dom: 19.2.0
  react-redux: ^9.2.0
  "@reduxjs/toolkit": ^2.11.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  socket.io: ^4.8.1
  socket.io-client: ^4.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  "@tabler/icons-react": ^3.0.0
  tsconfig-paths: ^4.2.0
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsup: ^8.5.0
  turbo: ^2.5.6
  "@types/bcrypt": ^6.0.0
  "@types/cookie-parser": ^1.4.9
  typescript: 5.9.2
  typescript-eslint: ^8.40.0
  "@types/express": ^5.0.0
  "@types/express-session": ^1.18.2
  "@types/jest": ^30.0.0
  "@types/multer": ^2.0.0
  "@types/node": ^22.15.3
  "@types/passport": ^1.0.17
  "@types/passport-jwt": ^4.0.1
  "@types/passport-local": ^1.0.38
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/supertest": ^6.0.2
  uuid: ^8.3.2
  zod: ^4.1.9
