import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ProductSpotlight from "@/components/ProductSpotlight";
import APISession from "@/libs/api/server";
import StoreProvider from "@/providers/StoreProvider";
import { WebSocketProvider } from "@/providers/WebSocketProvider";
import { ColorSchemeScript, mantineHtmlProps } from "@pawpal/ui/core";
import lamoon from "@pawpal/ui/fonts/lamoon";
import sarabun from "@pawpal/ui/fonts/sarabun";
import { UIProvider } from "@pawpal/ui/provider";
import "@pawpal/ui/styles/global.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<React.JSX.Element> {
  const currentLocale = await getLocale();
  let session = null;
  let productFilters = null;

  try {
    const API = await APISession();

    // Fetch user session
    const authResponse = await API.auth.getProfile();
    session = authResponse?.data || null;

    // Fetch product filters for global use
    const filtersResponse = await API.product.getFilters();
    productFilters = filtersResponse?.success ? filtersResponse.data : null;
  } catch (error) {
    console.error("Failed to load initial data:", error);
    session = null;
    productFilters = null;
  }

  return (
    <html
      lang={currentLocale}
      {...mantineHtmlProps}
      suppressHydrationWarning
      className={`${sarabun.className} ${lamoon.className}`}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <ColorSchemeScript />
      </head>
      <body>
        <NextIntlClientProvider>
          <StoreProvider
            preloadedState={{
              auth: {
                user: session,
              },
              product: {
                filters: productFilters,
                isLoading: false,
                error: null,
              },
            }}
          >
            <WebSocketProvider>
              <UIProvider locale={currentLocale}>
                <Navbar />
                <ProductSpotlight />
                {children}
                <Footer />
              </UIProvider>
            </WebSocketProvider>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
