import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { APIWithToken } from "@/libs/api";
import UIProvider from "@/providers/UIProvider";
import { ColorSchemeScript, mantineHtmlProps } from "@pawpal/ui/core";
import "@pawpal/ui/styles/global.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Sarabun } from "next/font/google";
import { cookies } from "next/headers";

const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-sarabun",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  const { data: session } = (token &&
    (await APIWithToken(token).getProfile())) || {
    data: null,
  };

  return (
    <html
      lang="en"
      {...mantineHtmlProps}
      suppressHydrationWarning
      className={sarabun.className}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <ColorSchemeScript />
      </head>
      <body>
        <NextIntlClientProvider>
          <UIProvider>
            <AuthProvider session={session}>
              <Navbar />
              {children}
              <Footer />
              {auth}
            </AuthProvider>
          </UIProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
