// Re-export icons from @tabler/icons-react
export {
  IconCheese as IconActivity,
  IconList as IconAll,
  IconAppWindow,
  IconArchive,
  IconAsterisk,
  IconBox,
  IconBrandApple,
  IconBrandFacebook,
  IconBrandGoogle,
  IconBrandSteam,
  IconCarouselHorizontalFilled,
  IconCategory,
  IconCategoryFilled,
  IconSwitch2 as IconChange,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconClockHour4,
  IconClockHour4Filled,
  IconPaw as IconCoin,
  IconCreditCard,
  IconCreditCardFilled,
  IconCurrencyBaht,
  IconDashboard,
  IconDashboardFilled,
  IconTrash as IconDelete,
  IconDeviceFloppy,
  IconPencil as IconDraft,
  IconGripVertical as IconDrag,
  IconPencil as IconEdit,
  IconExternalLink,
  IconEye,
  IconAdjustments as IconFilters,
  IconBolt as IconFlashsale,
  IconFolder,
  IconFolderFilled,
  IconPacman as IconGames,
  IconGripVertical,
  IconHelp,
  IconHistory,
  IconHome,
  IconInfoHexagon as IconInfo,
  IconInfoCircle,
  IconKey,
  IconLanguage,
  IconLink,
  IconLogin,
  IconLogout,
  IconMinus,
  IconBasket as IconOther,
  IconPhoto,
  IconPlus,
  IconWorld as IconPublish,
  IconShare3 as IconPublishShare,
  IconQrcode,
  IconReceiptDollarFilled,
  IconReceiptFilled,
  IconManualGearboxFilled as IconRoleFilled,
  IconCalendarEvent as IconSchedule,
  IconSearch,
  IconSettings,
  IconShieldCheckFilled,
  IconShoppingBag,
  IconShoppingCart,
  IconShoppingCartFilled,
  IconBrandSoundcloud as IconStreaming,
  IconTagsFilled,
  IconMoon as IconThemeDark,
  IconSun as IconThemeLight,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserBolt,
  IconUserFilled,
  IconUserSearch,
  IconPaw as IconWork,
  IconX,
} from "@tabler/icons-react";
