// Re-export icons from @tabler/icons-react
export {
  IconCheese as IconActivity,
  IconList as IconAll,
  IconBrandApple,
  IconBrandFacebook,
  IconBrandGoogle,
  IconBrandSteam,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconPaw as IconCoin,
  IconCreditCard,
  IconDashboard,
  IconBolt as IconFlashsale,
  IconPacman as IconGames,
  IconHelp,
  IconHistory,
  IconHome,
  IconKey,
  IconLanguage,
  IconLogin,
  IconLogout,
  IconMinus,
  IconBasket as IconOther,
  IconPlus,
  IconSearch,
  IconSettings,
  IconShoppingBag,
  IconBrandSoundcloud as IconStreaming,
  IconMoon as IconThemeDark,
  IconSun as IconThemeLight,
  IconUser,
  IconPaw as IconWork,
} from "@tabler/icons-react";
